version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    env_file:
      - .env
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    env_file:
      - .env
    depends_on:
      - mongodb
    ports:
      - "${MONGO_EXPRESS_PORT}:8081"

volumes:
  mongo_data:
